meeb/tubesync

- README.md
`implemenations` --> `implementations`
> README.md - Line: 15 - Spelling Error

- Dockerfile
Fixes #134 
I still have other errors (#135) after this with committing transactions but at least it connects to the database :) Will look into it some more if I have time later this week.
> Add libpq5 to docker image

- README.md
Corrected various spelling and grammar errors on the README.md file. Utilized a spell checker to verify.
> Correcting various spelling and grammar errors

- Dockerfile
Due yt-dlp recomendation [about ffmpeg distro](https://github.com/yt-dlp/yt-dlp#strongly-recommended), i suggest in this PR switch to yt-dlp latest distros.
Default distro FFMPEG s 3.X+, Latest yt-dlp patched distros is 5+ with [known solved problems](https://github.com/yt-dlp/FFmpeg-Builds#patches-applied)
After testing for two weeks different yt-dlp latest versions and latest ffmpeg software for about 15 channels, I Noticed reducing of generic errors like
`Failed to download media: ZAPvHphwiUw (UUID: 0d99a76d-bc19-487f-bfa3-11d702870611) to disk, expected outfile does not exist: /downloads/video/<vidfile.mkv>` right from ffmpged upgraded version (with current yt-dlp fixed in this repo).
Using yt-dlp manually in container also start working for previous failed videos with no errors after …
> Change ffmpeg from ytdlp

- tubesync/sync/views.py
This PR is a sanity/safety check against trying to put files into a directory outside of the DOWNLOAD_ROOT folder, causing issues like 
```
Internal Server Error: /source-update/55317d1e-9db4-4f10-8c6c-62f3763cafa8
Traceback (most recent call last):
...
raise SuspiciousFileOperation(
django.core.exceptions.SuspiciousFileOperation: The joined path (/tmp/2019-05-08_aaaa_dont-you-want-me-feat-such_i7ouv9AyB_o_opus.ogg) is located outside of the base path component (/home/kuhnchris/tubesync/tubesync/media)
```
this is especially problematic whenever you already downloaded files and try to "move" the folder, causing this to be stuck and having to go to `django-admin` to fix this issue.
> Add check against folders outside of DOWNLOAD_ROOT

- .github/workflows/ci.yaml
Removes the automatic pull request build due to failing for the regular contributors (aside from @meeb); solves #329
> Remove automatic builds on pull_request

- tubesync/sync/tasks.py
- tubesync/sync/tests.py
Current implementation of cleanup_old_media loads *all* downloaded media objects into memory and then filters them in code. This results in large memory consumption (5+ GB for a library of 15K+ media items).
This PR moves filtering to the database query.
> in cleanup_old_media, filter in database rather than in Python

- tubesync/sync/tests.py
Was working on getting my local dev environment working and ran into this.
> Use assertEqual as pluralized doesn't exist

- tubesync/sync/models.py
> Accept '-' in sub_langs

- .gitignore
- README.md
- tubesync/sync/models.py
- tubesync/sync/tests.py
- tubesync/tubesync/settings.py
This PR introduces a new environment variable, `TUBESYNC_DIRECTORY_PREFIX`, to enhance the flexibility of download directory configurations in TubeSync. Additionally, it updates the relevant documentation and tests to reflect this new feature.
---
1. **New Feature**:
- Added `type_directory_path` property to support two directory modes:
- `default`: Keeps the original behavior where audio and video files are stored in their respective directories.
- `flat`: Places all files in the root directory.
2. **Validation**:
- Added validation for incorrect or malformed `TUBESYNC_DIRECTORY_PREFIX` values to prevent runtime errors.
3. **Tests**:
- Created tests for the `type_directory_path` method, covering:
- Default behavior.
- Flat directory mode.
4. **Documentation**:
- Updated the README to …
> Add Support for TUBESYNC_DIRECTORY_PREFIX Environment Variable

- tubesync/sync/filtering.py
- tubesync/sync/models.py
> Adjust days_to_keep logic

- tubesync/tubesync/settings.py
This was from #572 but isn't needed with the later modifications.
> Remove audio / video directory modification

- tubesync/sync/models.py
Make the checks against the sources filter text case insensitive.
> Ignore case when checking the filter

- tubesync/sync/models.py
- tubesync/sync/templates/sync/media-item.html
- tubesync/sync/tests.py
- tubesync/sync/views.py
> Fix paths for when filename includes sub-directories

- tubesync/tubesync/wsgi.py
> Treat static_url the same as other URLs

- tubesync/sync/views.py
I am tired of links copied from YouTube not working without adjustments.
> Add youtube.com as a valid domain

- tubesync/sync/models.py
> DRY {json,nfo,thumb}name functions

- tubesync/sync/fields.py
Using the separator that was chosen is the biggest fix.
> Fix CommaSepChoiceField

- tubesync/sync/youtube.py
These are all optimizations:
- `writethumbnail`: for EmbedThumbnail to use
- `check_formats`: to save requests
- `overwrites`: to keep the first version of the video
- sleep intervals to slow down our tasks only for video downloads
> Add `ytopts`

- tubesync/sync/tasks.py
This method of changing `verbose_name` didn't result in any visible changes.
I would still like a way to display the countdown on the tasks page.
> Remove code that didn't work

- tubesync/sync/tasks.py
This is ready for review and merging.
Currently merged into my `test-2` branch and included in my next test image.
> Do not delete tasks that are currently running

- tubesync/sync/utils.py
- `heatmap`: is a huge list of tiny "chapters" used to display popularity of sections of the video
- `requested_subtitles`: also has a URL that expires
> Add more keys to filter

- tubesync/sync/hooks.py
> Add status text to the download task

- tubesync/sync/signals.py
This should mitigate the worst effects of #660 on my system.
> Do not schedule additional `download_media` tasks

- tubesync/sync/youtube.py
> Control `writethumbnail` with `embed_thumbnail`

- tubesync/sync/signals.py
Moved the save of media to the end of the function.
Fixes #141 #280 #361
> Skip downloaded media that was deleted

- tubesync/sync/hooks.py
> Find the correct media instance from hooks

- tubesync/sync/signals.py
- Remove unused imports
- Rename `Source.directory` when it changed
- Recreate the index task when `Source.name` was changed
- Distinguish the log message for the first time the index task is scheduled
- Delete more of the `Media` tasks when the media is deleted
Fixes #718
Fixes #721
> Review of signals.py

- tubesync/sync/models.py
> Select a combined format if nothing else is available

- tubesync/sync/filtering.py
- tubesync/sync/models.py
- tubesync/sync/tasks.py
- tubesync/sync/youtube.py
> Add and use `refresh_formats`

- tubesync/sync/signals.py
I think this is not only possible, but happens regularly.
> Log not existing source pre save

- .github/workflows/ci.yaml
- Pipfile
- patches/background_task/models.py
These are the changes used to build:
`ghcr.io/tcely/tubesync:django-5`
See also:
- #754
> Upgrade to 1.2.8 for Django 5 support

- tubesync/sync/models.py
> Access `posix_epoch` correctly

- tubesync/sync/models.py
Included the fix from #770 as well as removing an annoying debug log line.
Fixes #768
> Check for the cached dictionary first

- tubesync/sync/management/commands/import-existing-media.py
> Store `Media.downloaded_filesize` for imported files

- config/root/etc/nginx/nginx.conf
- tubesync/tubesync/settings.py
> CSRF Fixes for Django 5.1

- tubesync/sync/templates/sync/tasks.html
- tubesync/sync/views.py
> Add `pagination` for scheduled tasks

- tubesync/sync/models.py
- tubesync/sync/signals.py
Renaming works, and also my files aren't all skipped for being located in the wrong directory anymore.
Fixes #798
> Rename to a temporary path then final destination

- tubesync/sync/templates/sync/tasks.html
- tubesync/sync/utils.py
- tubesync/sync/views.py
After #790, I wasn't seeing tasks with errors.
> Display task errors from the current page

- config/root/etc/nginx/nginx.conf
- tubesync/tubesync/gunicorn.py
Fixes #34 
Fixes #454 
Fixes #748
> Long web requests

- .github/workflows/ci.yaml
This allows easy access to the step output variables.
> Name the buildx step

- tubesync/sync/management/commands/import-existing-media.py
> Set `Media.download_date` for imported files

- tubesync/sync/choices.py
> Fix 2160 resolution label

- tubesync/sync/views.py
> Filter latest downloads with `download_date IS NOT NULL`

- tubesync/sync/tasks.py
- tubesync/sync/youtube.py
Hopefully, these changes help #817 & #820.
> Increase database efficiency

- tubesync/sync/signals.py
> Improve checking media efficiency

- tubesync/sync/signals.py
- tubesync/sync/tasks.py
> Reorder checking all media to after indexing

- tubesync/sync/signals.py
> Use '/downloads' instead of '/' for odd cases

- tubesync/sync/models.py
> Increase episode number calculation speed

- tubesync/common/utils.py
- tubesync/tubesync/local_settings.py.container
- tubesync/tubesync/settings.py
`os.getenv` makes no guarantees about the return type for default values.
> Better environment variable support for settings

- .gitignore
- tubesync/sync/management/commands/delete-source.py
- tubesync/sync/models.py
- tubesync/sync/signals.py
- tubesync/sync/tasks.py
- tubesync/sync/views.py
> Improve deleting sources

- tubesync/sync/signals.py
> Clean up more tasks for deleted sources

- Dockerfile
Merging #831 before this pull request is likely a good idea.
> More Docker cache hits

- tubesync/sync/models.py
> Prevent `filename` from beginning with `/`

- tubesync/sync/signals.py
- tubesync/sync/tasks.py
Currently, these tasks are creating an error.
> Better indexing of inactive sources

- tubesync/sync/models.py
> Add a default thumbnail URL before metadata is available

- tubesync/sync/tasks.py
Fix build errors
https://github.com/meeb/tubesync/actions/runs/13939040136
> fixup: indentation

- tubesync/sync/tasks.py
> Thumbnail download can proceed without metadata

- tubesync/common/static/styles/tubesync.scss
- tubesync/sync/templates/sync/sources.html
> Apply the suggested "Sync Now" changes

- tubesync/common/utils.py
- tubesync/sync/hooks.py
- tubesync/sync/tasks.py
> Clean `verbose_name` when a repeating task did not complete

- patches/background_task/models.py
https://github.com/meeb/tubesync/actions/runs/14076459509/job/39420215410#step:6:150
Documentation:
https://docs.djangoproject.com/en/5.1/topics/db/queries/#retrieving-objects
> fixup: use the class instead of an instance

- tubesync/sync/management/commands/delete-source.py
- tubesync/sync/management/commands/reset-tasks.py
- tubesync/sync/signals.py
- tubesync/sync/tasks.py
- tubesync/sync/tests.py
- tubesync/sync/views.py
> Set priority in tasks.py

- tubesync/sync/tasks.py
> Use a task per instance for `Media.refresh_formats`

- tubesync/sync/templates/sync/dashboard.html
> Add renaming feature warning to the dashboard

- tubesync/sync/youtube.py
> Extract audio from `webm` downloads

- tubesync/sync/mediaservers.py
> POST to `/Items/{ID}/Refresh`

- README.md
> Add file renaming warning to README.md

- tubesync/sync/fields.py
I want a map of which functions are called,
when they are called,
and from which class they were defined.
These things are still not clear enough for me.
Fixes #960
> Fix `dumpdata` output

- .github/workflows/ci.yaml
- Dockerfile
Read more at:
* https://github.com/debuerreotype/docker-debian-artifacts/issues/126
* https://github.com/debuerreotype/debuerreotype/pull/178
> Add /etc/apt/apt.conf.d/docker-disable-pkgcache

- tubesync/sync/migrations/0032_metadata_transfer.py
- tubesync/sync/models.py
Well, that was a disappointing upgrade.
I remember reading about some limitations with the synthetic models, but I guess I didn't understand well enough.
We must use the real models to do the data migration.
> Use the actual model for data migration

- tubesync/sync/templates/sync/media-item.html
- tubesync/sync/urls.py
- tubesync/sync/views.py
I've wanted this in the UI for a bit of time now.
I'm welcoming changes to make it look better, but I at least want it to function correctly first.
For #997
> Add redownload thumb link

- tubesync/common/errors.py
- tubesync/sync/tasks.py
- tubesync/sync/utils.py
> Add `NoThumbnailException`

- docs/other-database-backends.md
> Add more details about saving database entries

- docs/other-database-backends.md
> Use `POSTGRES_DB` instead of `init.sql`

- tubesync/sync/forms.py
- tubesync/sync/templates/sync/task-schedule.html
- tubesync/sync/templates/sync/tasks.html
- tubesync/sync/urls.py
- tubesync/sync/views.py
This is starting out as a "run now" link for each scheduled task on the tasks page.
See also:
* #152
* #201
* #840
Fixes #840
> Add a start link to scheduled tasks

- tubesync/sync/youtube.py
> Let `missing_pot` formats download after testing

- tubesync/sync/signals.py
> Clean up extra metadata rows

- tubesync/sync/models/media__tasks.py
- tubesync/sync/tasks.py
> Downloading media fixes

- tubesync/sync/models/_private.py
- tubesync/sync/models/media.py
- tubesync/sync/utils.py
> Renaming was removing too many extensions

- Dockerfile
```
#51 28.47 removed '/tmp/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.11/site-packages/pip-25.1.1.virtualenv'
```
> Move the copied `HOME` to the `tmpfs`

- tubesync/sync/models/metadata.py
> Set a value when `Media.published` is `None`

- .github/workflows/ci.yaml
@meeb
This should push the missing release tags for you.
> Push missing release tags from previous workflow failures

- tubesync/restart_services.sh
```
/app/restart_services.sh \
background-task-workers \
gunicorn \
nginx \
huey-consumers
```
> Resolve bundles in restart_services.sh

- tubesync/sync/signals.py
> Re-work the re-use of old metadata after deletion

- .github/workflows/ci.yaml
Also, disabled the `docker push` step for tags.
> Remove the `docker pull` operations from info

- tubesync/sync/models/media.py
- tubesync/sync/models/source.py
- tubesync/sync/templates/sync/_mediaformatvars.html
- tubesync/sync/tests.py
I am tired of creating this myself from the parts. This way I can just add a zero, much easier.
> Add a convenience format: `yyyy_0mm_dd`

- tubesync/sync/youtube.py
- tubesync/tubesync/settings.py
> Ignore `TUBESYNC_WORKERS` entirely

- tubesync/sync/views.py
> Force `media_source.target_schedule` to have a value

- tubesync/common/huey.py
I found this [guide](https://docs.python.org/3.10/howto/descriptor.html#properties) useful for understanding how the `property` built-in works.
> Add the `TaskLock.acquired` property

- tubesync/common/huey.py
Please merge this as soon as you can.
> Releasing the lock to immediately take it again is a silly mistake

- tubesync/sync/models/media__tasks.py
> Provide all keys to `format`

- tubesync/sync/views.py
> Update `TaskHistory.scheduled_at` when scheduling tasks

- tubesync/sync/templates/sync/tasks.html
- tubesync/sync/views.py
> Reschedule using `TaskHistory`

- tubesync/common/migrations/0004_alter_taskhistory_task_id.py
> Log any index errors

- tubesync/common/templates/pagination.html
- tubesync/sync/views.py
> Use the last page for higher page numbers

- tubesync/sync/management/commands/import-existing-media.py
> Import metadata from a `.info.json` file

- tubesync/sync/tasks.py
> Upgrade downloaded when a better format is available

- tubesync/sync/tasks.py
- tubesync/tubesync/settings.py
> Add the `VIDEO_HEIGHT_UPGRADE` setting

- tubesync/sync/views.py
I didn't manage to beat the "or" variant of the search plan in my testing.
I'm happy to try any other improvements that you can think of though.
> Faster search queries

- tubesync/common/huey.py
> Ignore tasks where the first argument is not a UUID

- tubesync/sync/models/media.py
> Do not rename the current `Media.media_file`

- tubesync/common/errors.py
- tubesync/common/utils.py
- tubesync/sync/tasks.py
> Include more information when a key is missing

- tubesync/tubesync/settings.py
> Stop trying to use the `ios` client
