meeb/tubesync

tubesync/sync/models.py

One of my first questions while evaluating tubesync was what format options are available. 
I added format descriptions to the media format help_text based on the options I see in the models.
Edit: I am not sure why the last pipeline is failing, My changes should not relate to that.

Added format descriptions.

---

tubesync/sync/tasks.py

When looking for existing media objets during source indexing, the query should match both the key (the video's ID) and the source. Otherwise, a media object with a given key can only ever exist once, which breaks the case where multiple playlists share a video.

Fix meeb/tubesync#90: Match media on source and id

---

tubesync/sync/tests.py

Related to #88: Fix 4320p in test data.
Just a small fix to the test data. The tests pass with or without the change, but I discovered that `RESOLUTION_MAP` has the key `SOURCE_RESOLUTION_4320P`, which is case-sensitive with a lower-case `p`. If future changes are made that cause the tests to fail, this fix will eliminate one potential reason for failure due to bad data.

Related to #88: Fix 4320p in test data.

---

tubesync/sync/youtube.py

- Provides inbuilt sponsorblock support via the postprocessor
- Writes sponsorblock as the chapter file
- No removal of segments or configuration options currently (I'm not skilled enough in Django)

feat: initial sponsorblock support

---

.gitignore
README.md

Just a small addition as I was locally trying to get up the development environment (instead of using a .devcontainer/container for developing) and ran across this weird error:
```
(tubesync) kuhnchris@ERIKA-MINIPC:~/tubesync$ pipenv install
Pipfile.lock not found, creating...
Locking [packages] dependencies...
Building requirements...
Resolving dependencies...
✘ Locking Failed!
⠧ Locking...
ERROR:pip.subprocessor:[present-rich] python setup.py egg_info exited with 1
[ResolutionFailure]:   File "/home/kuhnchris/.local/lib/python3.10/site-packages/pipenv/resolver.py", line 811, in _main
[ResolutionFailure]:       resolve_packages(
[ResolutionFailure]:   File "/home/kuhnchris/.local/lib/python3.10/site-packages/pipenv/resolver.py", line 759, in resolve_packages
[ResolutionFailure]: …
```

Update README-FAQ regarding `Locking Failed`

---

tubesync/sync/templates/sync/media-item.html

Strictly speaking you *can* use the `<video>` player for `<audio>`, but it creates a huge gap and makes preview pretty badly usable IMHO.
instead of:
(yes, this is a cosmetic change; low prio)

<audio>-player instead of <video> for audio only

---

tubesync/sync/views.py

```This is a development change only - no changes on prod!```
... also requires setting `PROVIDE_FILES_DIRECTLY = True` in `local_settings.py` .
With this change, the entire package can be self-contained to test and develop without using a `docker` or `devcontainers` container.

(dev only) allow file download directly from django

---

tubesync/sync/models.py

Content type was throwing error when `video_type` was set to "Audio only". 
This rectifies this, not 100% sure if it's better, but it's better than a dump.
I assume there is a `downloaded_video_codec` aswell, we could use that and split it accordingly (OPUS/VP9) - let me know how you'd prefer to handle this.

Fix bug getting content_type for "audio only"

---

tubesync/common/static/styles/fontawesome/_icons.scss
tubesync/common/static/styles/fontawesome/_variables.scss
tubesync/common/static/styles/tubesync.scss
tubesync/sync/templates/sync/sources.html
tubesync/sync/templates/sync/tasks.html
tubesync/sync/urls.py
tubesync/sync/views.py

This PR adds a nifty litte "Sync" button that schedules a reindex.
I did *not* create a new View(class) for this, I only split the get() path into "sync" and "not sync".
I hope this is fine by you  @meeb ? If not please let me know and I will try to create a new View for it.
Also, this fixes a weird bug that kept showing that a task is "reoccuring" alltho it's "repeat" property is set to 0 in the task overview. Let me know if I shall split that into 2 PRs.
Also includes the additional "arrow-rotate-right" from FontAwesome, for some reason that one wasn't in the SCSS? 🤔 
It's not a "PRO" icon, so I'm just a bit confused if this is just a `lite` version of FA.
Also, this changes the CSS of the `container-item` into a `flex` container. If you want to avoid doing this, let me know, and I'll …

"Sync now" button

---

tubesync/sync/tasks.py

See above. As discussed in #333 it's a dead function left over after some refactoring of the code.

del `delete_index_source_task` calls - solves #333

---

tubesync/common/static/styles/materializecss/components/forms/_checkboxes.scss
tubesync/common/static/styles/tubesync.scss

Make the (i) less stuck to the text.
before:
after:
(yes, this is another feature I work on in the 1st screenshot, sorry, I only had that screenshot on hand right now.)
(also, yes, this is cosmetic, so low priority) 🔽

align (i) better with text (+ checkbox less wide)

---

tubesync/common/static/styles/_fonts.scss
tubesync/common/static/styles/_variables.scss

Texts which had the `font-weight` set to `bold` were displayed in normal thickness (*chromium based - macOS*).
I renamed the font-family `roboto-{light,medium,bold}` to just `roboto`, which should automatically select the correct font-family based on font-weight.
---
<details>
<summary>Before</summary>
</details>
<details>
<summary>After</summary>
</details>

fix: bold font weight

---

tubesync/sync/views.py

This fixes the latest downloads page to continue to work even after you have manually imported media.

Fix #364 by checking the filesize is not null.

---

Dockerfile

It looks like the ffmpeg version provided in the Dockefile is no longer available in the origin repo: (https://github.com/yt-dlp/FFmpeg-Builds/releases/tag/autobuild-2023-04-13-12-52)
This pr fixes the build issues by using the latest available autobuild version of the ffmpeg from the origin repo:  https://github.com/yt-dlp/FFmpeg-Builds/releases/tag/autobuild-2023-05-03-12-37
cc: @meeb

fixing unavailable ffmpeg version

---

tubesync/sync/signals.py

This fix helps prevent #428 from resulting in the entire container being killed by the host. The timeout still occurs on the web browser, but importantly the delete task does complete whereas before the gunicorn worker timeout interrupts the task. Reloading the tubesync homepage after the timeout will now show the source as deleted. I've done this by ensuring that the gunicorn workers have a much longer timeout before being killed (10mins instead of 30 seconds), and by forcing the workers to be restarted. I think the key change is increasing the timeout but I think both are helpful in long-running applications (months of uptime).
As can be seen from the logs below, it's the gunicorn worker (pid 358) that ultimately causes the application to crash completely and the delete task to be …

Fix signals.py mistake

---

tubesync/sync/models.py
tubesync/sync/tests.py

Following #379 :
For Jellyfin to get information to sort the videos, I added the season and episode tags in the NFO file:
The season is always 1 if the source is a playlist and is the year of publication if the source is a channel
The episode is the position in the playlist or the number of the video in the year, sorted by publication date if the source is a channel
I tested it with a Docker container and found that it worked correctly but I couldn't run the test script so I changed the expected NFO without having it verified

Added season and episode tags in NFO to get Jellyfin displaying correctly

---

tubesync/sync/views.py

I have faced the issue with several pages - sources view and the dashboard - when I have relatively big channels synced. I have checked the queries and found out, that the column `metadata` is huge and makes the query extremely slow in the places where it is not required (100 ms vs 2-7 seconds). The easiest workaround is to exclude the field from the selection.

Optimized source page and dashboard loading

---

tubesync/sync/signals.py
tubesync/sync/tasks.py

Hey, I'm playing around with tubesync and I'm trying to add a couple of large channels and bumped into the #260 issue.
Would something like this work? I'm not really familiar with django or the process that media and tasks go through so I might be very off base here. I am also making the assumption that media.skip has already been set on the media entry before we get to the signaling for the thumbnails, which might not be correct.
I'm currently having some issues building the container or even installing deps locally on macos so I haven't tested this; I blame the fact it's pretty late here and will give it another shot tomorrow.
Any issues and ideally suggestions for getting this right would be appreciated!
Regards, George

Skip metadata and thumbnails if they are past the cutoff date

---

docs/custom-filters.md
tubesync/sync/filtering.py
tubesync/sync/overrides/custom_filter.py

Fix #509
Allow semi easy override of filtering logic with custom python code so it can be extended by end users
Have a look and let me know what you think. I'm not entirely sure it's needed, but it is a solution to #509

Allow semi easy addition to filtering logic

---

.dockerignore
Dockerfile
README.md

Split installation of services, dependency installation, and code building steps so we can make the most use of docker build caches. When only making changes to code, this can now use the build cache to build an image in <10s. This means that if the base dependencies (redis/nginx etc) don't change between versions, the changed layers to download are less, allowing for quicker updates.
This also makes it easy to see runtime deps vs build only deps, so we can uninstall the packages we don't need once the pipenv is setup.
Dive report on ghcr.io/meeb/tubesync:latest with 10 layers
```
Total Image size: 621 MB             
Potential wasted space: 26 MB                  
Image efficiency score: 96 %
```
Dive report with these changes, with 12 layers, but quicker rebuild time, and also improved …

Docker build caching

---

tubesync/sync/migrations/0025_add_video_type_support.py
tubesync/sync/models.py
tubesync/sync/templates/sync/source.html
tubesync/sync/views.py

Tweaked the original code a little and added option to only index streams.

Add support for indexing Streams

---

tubesync/manage.py

```shell
root@tubesync-6c8bb86b79-s88cd:/app# /usr/bin/env python
/usr/bin/env: ‘python’: No such file or directory
root@tubesync-6c8bb86b79-s88cd:/app# /usr/bin/env python3
Python 3.11.2 (main, May  2 2024, 11:59:08) [GCC 12.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> 
```

Fix python version in manage.py

---

Dockerfile

Moved the hashes to build arguments.
Optimized the build by removing an unnecessary tar command.
Recorded the versions in the final container.
Used shell functions to remove repeated similar commands.
Used a copy of `/root` in `/tmp` instead of recreating it.
Cleaned up old unset variables.
I'm unsure why `ARCH` is being used, so I kept it. Using `TARGETARCH` instead makes more sense to me. Also, `ARCH44` was a complete mystery variable to me, so I removed it.
I'd suggest squashing these commits when you merge this. I was working through the website, so they are more like save points than discrete changes.

Reworked Dockerfile

---

README.md
tubesync/tubesync/settings.py

"Get next best resolution or codec instead" has a minimum quality capped by `VIDEO_HEIGHT_CUTOFF` with no method to bypass it. This is undesirable when adding a Playlist source, where audio-only is not desired, but that would be the only way to trigger a download.
Allow video heights down to 120px to allow "next best" to fallback as far as necessary.
Possible better ways to resolve this:
- Have a configuration in the Source to define the lowest tolerable resolution (optionally allowing audio-only fallback)
- Expose a page in the webapp that allows global configuration, would require settings persistence to db
Both of these possibilities seem potentially desirable, but are much larger scope than this patch. If there's appetite, I may be willing to take on one of those projects.

Configure minimum permitted video height with VIDEO_HEIGHT_CUTOFF env var

---

tubesync/sync/matching.py

This block is in the not 60 fps case, so checking for a match outside of that condition doesn't make sense to me or fit the comment.

Adjust to correct 60 fps case

---

tubesync/sync/utils.py

The function should return 'VP9' for:
- vp9.1.2.3
- vp09.4.5.6
As well as other variations.
It also works for avc01 or av01, or any others that fit the pattern.

Handle STR0NNN in a generic way

---

tubesync/sync/matching.py
tubesync/sync/utils.py

* Stop sorting audio formats
The list we received from `youtube-dl` is better than bitrate sorting
* Include candidates by height, not format (`format_note`)
* Populate the empty format when the height matched
* Match `VP09` to `VP9` to avoid unnecessary fallback

Sort video formats by height and bitrate

---

tubesync/sync/filtering.py

This isn't the logic we should be using.
Just stop using it until the function is comparing the proper dates.
See: #570

Disable checking against days to keep

---

tubesync/sync/utils.py

This is more atomic and allows for checking `filepath` with `file_is_editable` before replacing the original file.

Use tempfile for write_text_file

---

tubesync/sync/youtube.py

As far as I can tell, this option only caused a lot of JSON output to be logged.

Remove forcejson option

---

tubesync/tubesync/settings.py

Avoids a warning:
`Overwriting params from "color" with "no_color"`

Switch to color option

---

tubesync/sync/models.py

We stored a stripped title string in the database, just use that instead of `.name` and calling `.strip()` again.

Use title from DB

---

tubesync/sync/tasks.py

Channels with thousands of videos, that won't be downloaded, create large blocks in the logs without this.

Only log new media

---

tubesync/sync/models.py
tubesync/sync/youtube.py

Catching this and checking the message may be the best way to skip members only videos.
~My current understanding of the situation is that this won't work.~ 🙁 The documentation was inaccurate, so setting `ignoreerrors` to `False` caused the exception to be raised. 👍
I can get a better result, by setting `ignore_no_formats_error` to `True` when fetching the metadata.
Actually using that is likely to have unintended consequences in the future. I'd much rather find a way to only accept no formats for members only videos that can't be downloaded.
The next idea is to ignore the error, then parse the results to check for `"availability": "subscriber_only",` before accepting them as useful.
Fixes #584

Handle raise_no_formats exception

---

tubesync/sync/filtering.py

Logically these functions can only mark media instances as skipped, so running them for media instances that are already marked that way is a waste of resources.

Do not try to skip already skipped media

---

tubesync/sync/youtube.py

```
{key}: This video is available to this channel's members on level: Level 2: Contributor (or any higher level). Join this YouTube channel from your computer or Android app.
```

Match another variation of the message

---

tubesync/sync/tasks.py
tubesync/sync/utils.py

This should reduce unnecessary errors like those seen in #609.
As proposed in https://github.com/meeb/tubesync/issues/609#issuecomment-2573270228 this also logs a warning on `PermissionError` exception instead of letting that reschedule the task.

Don't chmod a+r when it already has those permissions

---

Dockerfile

Running the ffmpeg in an earlier (hopefully cached) layer should clean up the logs a bit.
On a related note, shadowing the environment variable was causing some confusing log output, so stop doing that as well.

Test and log ffmpeg version output earlier

---

tubesync/sync/models.py

Is there any reason not to use `filepath` here?

Simplify directory_path for Media

---

Dockerfile

* Create a s6-overlay-extracted stage to copy from
This was largely inspired by: @socheatsok78
Our downloaded files are checked where that version doesn't do any verification of the downloads.
* Update ffmpeg to the first build with checksums.sha256
* Create a ffmpeg-extracted stage to copy from
* Don't preserve ownership from the builder
I was sick of the extra work with ffmpeg builds.
So, I managed to get sums generated for those builds and now we don't need to manually fill out SHA256 hashes anymore.
Now to bump ffmpeg, we can just change the date.

Multi-stage docker build for ffmpeg & s6-overlay

---

tubesync/sync/models.py
tubesync/sync/tasks.py
tubesync/sync/tests.py
tubesync/sync/utils.py

~These functions aren't being used yet, they will be tested against my database before that happens.~
My testing went well.
I've added two new settings to let people easily try this out.
- `SHRINK_NEW_MEDIA_METADATA` must be set to `True` for newly retrieved metadata to be filtered.
- `SHRINK_OLD_MEDIA_METADATA` must be set to `True` for loaded metadata to be updated with filtered metadata.
Please do try out whichever way is more useful for you.

Filter metadata to avoid storing excess text in the database table

---

Dockerfile

Use the form of health checking that doesn't involve an extra shell on every check.

Dockerfile health check without the shell

---

tubesync/healthcheck.py

This is only intended for use in containers, so we know where python3 should be installed.
This is called very often, so we should try to use as few resources as we can.

Avoid env for healthcheck

---

tubesync/sync/models.py

It's better to not have a rating than to create parsing problems.
An example of what is avoided:
```
<ratings>
<rating name="youtube" max="5" default="True">
<value>None</value>
<votes>16781</votes>
</rating>
</ratings>
```

Don't write 'None' in default rating

---

tubesync/sync/models.py

It's a bit odd that `mpaa` is used in a `.nfo` that also uses TV series and episode features, but whatever.

Don't write zero into MPAA in .nfo

---

Dockerfile

- Consolidate apk & apt commands
- Consolidate ENV layers
- Consolidate RUN layers
- Remove unused variables
- Remove packages that are no longer needed
- Bind mount /app/Pipfile
`/cache` is now a `tmpfs` mount that has a `cache` mount on top for `pipenv` to use.
`apt` has `cache` mounts in the standard places:
- /var/lib/apt
- /var/cache/apt
This should significantly speed up the `arm64` builds because two wheels were built on that architecture versus only one for `amd64` builds.

Cache for pipenv & apt

---

tubesync/sync/views.py
tubesync/sync/youtube.py

Yay! No more manual searching for channel IDs.
It fetches the channel ID with `yt-dlp` and switches the type from channel to channel-id for the pre-filled add source page.
This is basically as described in https://github.com/meeb/tubesync/pull/306#issuecomment-1384966047
Closes #306

Automated channel_id extraction

---

tubesync/sync/templates/sync/media-item.html
tubesync/sync/utils.py

The audio formats now look like this:
```
ID: 249-0, audio:opus @57.906k / 48000Hz French (France), low
ID: 249-1, audio:opus @58.154k / 48000Hz Portuguese (Brazil), low
ID: 249-2, audio:opus @58.204k / 48000Hz Spanish (United States), low
ID: 249-3, audio:opus @58.74k / 48000Hz Italian, low
ID: 250-0, audio:opus @74.628k / 48000Hz French (France), low
ID: 250-1, audio:opus @75.0k / 48000Hz Spanish (United States), low
ID: 250-2, audio:opus @75.001k / 48000Hz Portuguese (Brazil), low
ID: 250-3, audio:opus @75.602k / 48000Hz Italian, low
ID: 249-4, audio:opus @49.925k / 48000Hz English (United States) original (default), low
ID: 250-4, audio:opus @63.085k / 48000Hz English (United States) original (default), low
ID: 140-0, audio:mp4a.40.2 @129.474k / 44100Hz French (France), medium
ID: …
```

Better display for audio formats

---

tubesync/sync/views.py

This helps me easily view videos that have no matching formats because they are only for subscribers.

Display media we can't download as skipped

---

tubesync/sync/models.py

This prevents useless logged errors when there is no metadata available yet.

Default to valid JSON

---

config/root/etc/s6-overlay/s6-rc.d/tubesync-worker/run

Now that SponsorBlock is running, these jobs are using significant CPU resources.
Setting a nice level to let other things run better while `ffmpeg` is running seems wise.

Set a default nice level

---

tubesync/sync/youtube.py

I am seeing multiple ffmpeg processes that mess each other up.
I do not know why this is happening yet, but for now let them operate in their own temporary directories.

Use a temporary directory per task

---

tubesync/sync/youtube.py

The quick fixup works, this is simply cleaner.

Use strings for `ytopts` paths

---

tubesync/tubesync/local_settings.py.container

`common.logger` imports `settings`
Creating a circular dependency causes the failure to load this file from `tubesync/settings.py`.
Without the change to `DEBUG` from this file the log level is `INFO` instead of `DEBUG` so none of those messages were showing.
This was broken by 20df9f4044a3c66f641b2de145efc1b15e0ece56.

Fix log.debug()

---

tubesync/sync/tests.py

Otherwise, environment variables can cause the `unfiltered` and `filtered` responses to match. This breaks the assumption that the asserts are depending upon.

Configure settings for this test

---

tubesync/sync/templatetags/filters.py

I must have been fixated on using `replace()`.
After already splitting the string, using the part we don't want seems silly.

Simply add the string we want

---

config/root/etc/s6-overlay/s6-rc.d/tubesync-init/run

We don't need to overcomplicate this.
`sh` and `bash` provide easy ways to set empty variables.
If it was exported already, doing that again won't hurt anything.
However, if we use the default because it wasn't set, we should export it or it becomes invisible after `exec` does its thing.
Not that the `manage.py` is looking for that variable or anything.

export `TUBESYNC_RESET_DOWNLOAD_DIR`

---

tubesync/sync/fields.py
tubesync/sync/migrations/0027_alter_source_sponsorblock_categories.py
tubesync/sync/models.py
tubesync/sync/templates/widgets/checkbox_option.html
tubesync/sync/tests.py

This is a great stopping point.
* Loading from the database and saving back to the database both work.
* The categories are displayed in the web user interface appropriately.
* Editing the `Source` from the web user interface is working.
* There are now tests checking for `sponsorblock_categories` remaining set after the various other `Source` checks.
Fixes #362 
Closes #668 #669

Rework `sponsorblock_categories` and `CommaSepChoiceField`

---

tubesync/sync/tasks.py

I thought this commit was already merged, but git claimed this line wasn't.
I don't think it matters if the `media.media_file.name` is blank here.
I made this mostly for completeness.

Also check for `media.media_file.name`

---

tubesync/sync/tasks.py

Starting on the smarter scheduling for upcoming videos.
This quick and messy solution appears to be working. The basic approach is sound.
I would still like to edit the task name from within the task function to display the remaining hours in the task list also.
Fixes #676

Wait for video premiere

---

tubesync/common/static/styles/_forms.scss
tubesync/sync/templates/widgets/checkbox_option.html

It turns out using a `div` in a06bd29f88d46eec86de071c3495d49d932f1707 broke the interface.
This is a better way.

Turn off the `text-transform` with a class

---

tubesync/sync/hooks.py
tubesync/sync/youtube.py

- Be more resilient about missing keys.
- Log the downloading state the first time through.
- Keep `hook.download_progress` under 100.
- Try to use `total_bytes_estimate` when `total_bytes` is not available.
~For multiple downloads, at the same time, this needs to be improved further.
Each download will need to track status independently.~
The key may need to be adjusted, but the basic support is already present.
Reference:
```
progress_hooks:    A list of functions that get called on download
progress, with a dictionary with the entries
* status: One of "downloading", "error", or "finished".
Check this first and ignore unknown values.
* info_dict: The extracted info_dict
If status is one of "downloading", or "finished", the
following properties may also be present:
* filename: The final …
```

Rework download progress hook

---

tubesync/sync/hooks.py

Now that fragments are properly reporting progress, the only slightly confusing part of the logged output is the sleep.
```
2025-02-07 21:08:49,916 [tubesync/INFO] [youtube-dl] downloading: [FILE]_vp9-opus.f605.mp4 - 25% of N/A at 128.42KiB/s, 00:28 remaining
2025-02-07 21:08:53,787 [tubesync/INFO] [youtube-dl] downloading: [FILE]_vp9-opus.f605.mp4 - 35% of N/A at 127.73KiB/s, 00:27 remaining
2025-02-07 21:08:59,072 [tubesync/INFO] [youtube-dl] downloading: [FILE]_vp9-opus.f605.mp4 - 45% of N/A at 81.94KiB/s, 00:30 remaining
2025-02-07 21:09:04,240 [tubesync/INFO] [youtube-dl] downloading: [FILE]_vp9-opus.f605.mp4 - 55% of N/A at 58.39KiB/s, 00:34 remaining
2025-02-07 21:09:09,920 [tubesync/INFO] [youtube-dl] downloading: [FILE]_vp9-opus.f605.mp4 - 65% of N/A at 92.47KiB/s, 00:25 …
```

Add & use functions from status classes

---

tubesync/sync/utils.py

After removing the assert, the old name was a bit confusing.

Rename the internal function

---

tubesync/sync/signals.py

https://github.com/meeb/tubesync/blob/8d89cc01f961b6440584d5984784e01881dfa900/tubesync/sync/signals.py#L263-L268
I think this was already covered by `all_related_files` at the end, but matching `*.vtt` files earlier won't hurt anything.
Fixes #416

Remove subtitles also

---

tubesync/sync/youtube.py

This is a dictionary with keys of `WHEN` and values are a `list` of commands for the `ExecPP` to run.

Allow `exec_cmd` dictionary to be configured in settings

---

tubesync/sync/signals.py

After #704, the `duration`, `published`, and `title` are all available before `metadata` has been retrieved.

We can filter before metadata

---

tubesync/sync/templates/sync/media-item.html

This is a user experience improvement.
Now, that I look at this again, that page should also be showing the date when media was downloaded.

Show publication date and the not truncated title

---

tubesync/sync/hooks.py

I've seen it, and the query looks fine.
```sql
SELECT "sync_media"."uuid", "sync_media"."created",
"sync_media"."source_id", "sync_media"."published",
"sync_media"."key", "sync_media"."thumb",
"sync_media"."thumb_width", "sync_media"."thumb_height",
"sync_media"."metadata", "sync_media"."can_download",
"sync_media"."media_file", "sync_media"."skip",
"sync_media"."manual_skip", "sync_media"."downloaded",
"sync_media"."download_date", "sync_media"."downloaded_format",
"sync_media"."downloaded_height", "sync_media"."downloaded_width",
"sync_media"."downloaded_audio_codec", "sync_media"."downloaded_video_codec",
"sync_media"."downloaded_container", "sync_media"."downloaded_fps",
"sync_media"."downloaded_hdr", "sync_media"."downloaded_filesize",
"sync_media"."duration", "sync_media"."title" …
```

Remove logging of the SQL

---

tubesync/sync/filtering.py
tubesync/sync/signals.py
tubesync/sync/tasks.py

~This probably needs a more nuanced solution.~
Ok. I think this handles the cases we need.
Fixes #723

Do not turn `Media.skip` off for already skipped media

---

tubesync/sync/signals.py
tubesync/sync/tasks.py

This is a user experience improvement and should also be more effective as well.
Having a task per download gives the user better insight into the progress of the renaming.
It also allows a new task to remove the queued task because the locked task no longer includes every media item.

Schedule a rename task per media item instead

---

tubesync/sync/models.py

This was the cause of many rename operations.

Be more consistent with `fmt`

---

tubesync/sync/management/commands/reset-tasks.py
tubesync/sync/tasks.py
tubesync/sync/views.py

This is an attempt to stop duplicated tasks from running at the same time.
See:
- #660

Add scheduling delays

---

config/root/etc/s6-overlay/s6-rc.d/tubesync-init/run

Setting the mode to the same value twice is only wasted effort.

Remove unnecessary `chmod` executions

---

tubesync/healthcheck.py

When I intentionally set a test container to be down, I really don't want it to be restarted because it was "unhealthy" for too long

Prevent unintended unhealthy restarts

---

tubesync/sync/models.py
tubesync/sync/youtube.py

So, after reading #147, I thought TEDx would be a good stress test for this.
My production container using `latest` is attempting to only index that channel.
`$` [docker container stats](https://docs.docker.com/reference/cli/docker/container/stats/) `--no-stream TubeSync PostgreSQL`
```
CONTAINER ID   NAME         CPU %     MEM USAGE / LIMIT     MEM %     NET I/O          BLOCK I/O         PIDS
42139b7cca00   TubeSync     97.73%    5.906GiB / 31.34GiB   18.85%    306GB / 12.6GB   5.02MB / 13.8MB   31
fc7cb3bd1893   PostgreSQL   4.28%     230.4MiB / 31.34GiB   0.72%     6.19GB / 302GB   0B / 8.19kB       18
```
The test container is already done indexing the last week of videos.
```
Index media from source "TEDx Talks"
Source: "181b3a4b-c955-41aa-bafb-0ca705fce2da"
Task ran at 2025-02-27 …
```

Use `yt-dlp` `daterange` option

---

Dockerfile

It turns out `apt` and friends don't play nicely with that variable.

Restrict `PYTHONPYCACHEPREFIX` to `pipenv`

---

Dockerfile

This is the dependency that takes so long to compile that it dominated every other part of the build time.
It's a ~12 MiB wheel when we compile from the latest source.

Speed up `arm64` builds

---

Pipfile

We need this to use the package added in #808.

Remove explicit `libsass`

---

Dockerfile

Checking before the copy doesn't help.
Fixes #804

Check the copied `nginx` configuration

---

patches/yt_dlp/patch/fatal_http_errors.py
tubesync/sync/youtube.py

To respect HTTP 429 errors, we need to provide additional arguments to a function called in the `YoutubeIE` class.
Fixes #849

Create `fatal_http_errors.py` patch

---

tubesync/sync/signals.py
tubesync/sync/tasks.py

SQLite is bad at concurrency, so we try to minimize the amount of time a transaction has the database locked to work around that limitation.
Fixes #834

Reduce the amount of time the database is locked

---

tubesync/sync/templates/sync/tasks.html

`run_at` is when it was eligible to be processed.
`locked_at` is when it was selected from the queue.
The delta between these two times is often quite large on my containers.

Use `locked_at` as it is closer to started

---

tubesync/sync/youtube.py

This is the cleanest way I found to change the behavior while everything is running.
Sometimes my proxy is misbehaving and I need to keep partial videos, other times it is better to start from scratch.
Restarting to change this only interferes with other longer running tasks.

Resume partial downloads unless the `.clean` file is found

---

.github/workflows/ci.yaml
Dockerfile
patches/background_task/models.py
tubesync/tubesync/settings.py

The node name for docker changes when creating a new container.
The PID can match after creating a new image if the start up sequence is the same.
~Using `docker restart` may still cause false positives for tasks still running.~
Used `boot_time` (from `/proc/kcore` mount) to determine if `locked_at` was before the current Docker start time.

Change the task expiration to 1 day

---

tubesync/full_playlist.sh
tubesync/sync/youtube.py

The idea for this is simple.
Check that we download all of the entries the playlist reported.
Rarely, a playlist result is too short for whatever reason. When this happens, and you are using "delete removed media" then a lot of media items will have been deleted.
Later, when the full playlist results are retrieved, all of those media items are being downloaded again.
We want to avoid this situation by skipping the index when the playlist is incomplete.
```
[tubesync/DEBUG] [info] Writing updated playlist metadata as JSON to: /config/cache/yt-dlp/infojson/playlist/postprocessor_[PLID]_100_876_temp.info.json                                  
[tubesync/DEBUG] [Exec] Executing command: /usr/bin/env bash /app/full_playlist.sh 'PLID' '876'
```
Failed playlists look like this:
```
File …
```

Add a post-processor to disallow partial playlist results

---

patches/background_task/management/commands/process_tasks.py

For:
```
Exception ignored in: <function Pool.__del__ at 0x7fc4a03159e0>
Traceback (most recent call last):
File "/usr/lib/python3.11/multiprocessing/pool.py", line 271, in __del__ 
File "/usr/lib/python3.11/multiprocessing/queues.py", line 371, in put 
AttributeError: 'NoneType' object has no attribute 'dumps'
```

Close the `ThreadPool` before exiting

---

tubesync/sync/matching.py

Playlist indexing can fail with
```
File "/app/sync/models.py", line 891, in get_format_str
video_match, video_format = self.get_best_video_format()
^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/app/sync/models.py", line 871, in get_best_video_format
return get_best_video_format(self)
^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/app/sync/matching.py", line 120, in get_best_video_format
video_formats = multi_key_sort(video_formats, sort_keys, True)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/app/sync/utils.py", line 191, in multi_key_sort
result.sort(key=key_func(key), reverse=reverse)
TypeError: '<' not supported between instances of 'float' and 'NoneType'
```
Defend against this case by ensuring all sort keys are present in any considered formats

Fix video format sorting in case of missing keys

---

tubesync/sync/youtube.py

A possible improvement on this quick fix is to create a Python post processor that handles the rename and updates the information for later post processors.
This would run before the `MoveFiles` post processor does its work.
This pull request includes changes targeting [`overwrites`](https://github.com/yt-dlp/yt-dlp/blob/349f36606fa7fb658216334a73ac7825c13503c2/yt_dlp/postprocessor/movefilesafterdownload.py#L38) in `MoveFiles` also.
Fixes #983

Add a post processor for after move

---

tubesync/sync/matching.py

Return the requested codec before matching the first available format
Fixes #990

Expand resolution matching to include height

---

tubesync/sync/migrations/0032_metadata_transfer.py

It seems odd for Python to insist that a key I am trying to remove must exist already.
At least there is a way to do it without the checks or try blocks.

Ignore `KeyError` when deleting keys

---

tubesync/sync/tasks.py

I've noticed that the newly replaced thumbnail isn't being used by my media server, because we never updated it.

Copy updated thumbnail next to media

---

tubesync/sync/youtube.py

I recently noticed that the combined format was matching for one of my sources, but the tasks were failing because it downloaded with the `.mp4` extension.

Remux video for combined format download

---

tubesync/sync/choices.py

Add `music.youtube.com` to the YouTube domains

---

tubesync/sync/signals.py

It is fine to schedule a download task when we might not need to because the task will either decide not to run itself or raise an exception outside of the post save signal handler.
https://github.com/meeb/tubesync/blob/73972c8b0c3f43e8490f310845e0a6d594ab8921/tubesync/sync/tasks.py#L605-L642
Fixes #1028

Log `OSError` when checking for existing media files

---

tubesync/sync/signals.py
tubesync/sync/tasks.py
tubesync/sync/tests.py

To optimize deletion of `Media` objects,
the `pre` and `post` signal handler functions are used together to save minimal information into a new instance that is marked as skipped.
Fixes #93

Create a media entry after deletion

---

tubesync/sync/forms.py
tubesync/sync/templates/sync/task-schedule.html
tubesync/sync/views.py

Use a widget to select `when` in the browser

---

tubesync/sync/views.py

This is what `Task.has_error()` is doing as well.
I was seeing rescheduled tasks counting toward the error total but not in the errors section on the tasks page.

Tighten `errors_qs` by checking `last_error`

---

Dockerfile

When `pipenv` installs it is using a virtual environment that `uv` created for it to run as a tool.

Install using `uv pip install`

---

tubesync/sync/models/source.py

Python is really inconsistent in so many places.
Fixes #1081

Use `datetime.weekday()` function

---

tubesync/sync/models/media__tasks.py
tubesync/sync/tasks.py

I'm not touching this further until after the tasks history is sorted out and the tasks page is updated.
However, I still want to benefit from the new queues, so here we are.

Create a path around `download_media_thumbnail`

---

tubesync/sync/management/commands/reset-tasks.py
tubesync/sync/signals.py
tubesync/sync/tasks.py
tubesync/sync/views.py

The idea here is to not use `repeat` at all.
Instead, the source is evaluated every hour to see if it should be indexed.
This should also let us stop deleting indexing tasks.
```
[2025-06-16 10:59:13,749] INFO:huey.consumer.Scheduler:208:Enqueueing periodic task sync.tasks.schedule_indexing: 88d70b27-2461-4b7c-9be1-bb7bc7c77e97 exp=1800 p=100.
[2025-06-16 10:59:32,823] INFO:huey:209:Executing sync.tasks.schedule_indexing: 88d70b27-2461-4b7c-9be1-bb7bc7c77e97 exp=1800 (2025-06-16 11:29:13.750442) p=100
[2025-06-16 10:59:32,945] INFO:huey:209:sync.tasks.schedule_indexing: 88d70b27-2461-4b7c-9be1-bb7bc7c77e97 exp=1800 (2025-06-16 11:29:13.750442) p=100 executed in 0.121s
```
```
[2025-06-16 12:59:26,448] INFO:huey.consumer.Scheduler:6350:Enqueueing periodic task sync.tasks.schedule_indexing: …
```

Schedule indexing tasks using `huey`

---

tubesync/sync/tasks.py

```
[tubesync/DEBUG] (<class 'django.utils.functional.lazy.<locals>.__proxy__'>, <class 'str'>, <class 'str'>)
```

Provide a string where it is expected

---

tubesync/sync/models/media.py

I haven't given this change great consideration.
If there is a reason not to allow Unicode, then please let me know.
@meeb Why are underscores disallowed?
Fixes #527

Add `allow_unicode=True` to `slugify`

---

tubesync/tubesync/settings.py

We only download one video at a time, so skipping over a failed download isn't something that we want.
The current default is: `only_download`
```py
>>> import yt_dlp
>>> default_opts = yt_dlp.parse_options([]).options
>>> default_opts.ignoreerrors
'only_download'
```

Turn off `ignoreerrors`

---

tubesync/tubesync/settings.py

Provide the default to eliminate:
```
[debug] [youtube] [pot:bgutil:http] No base_url provided,
defaulting to http://127.0.0.1:4416
```

Silence a silly logged message

---

tubesync/yt_dlp_plugins/extractor/cache-huey.py

When a cookies file is used, it makes sense to cache the token.
Without a cookies file, the token changes every time anyway, so a cache always misses.
This stores a key into the `huey` queue's storage for each token that it is asked to save.

[TubeSync-huey] Create cache-huey.py

---

tubesync/sync/views.py

The 12 hour limit may not be needed, but my task history rows are odd from testing at the moment.

Adjust the running tasks query set

---

tubesync/sync/tasks.py

When `Source.last_crawl` is updated and saved the `source_post_save` receiver function creates a `save_all_media_for_source` task.
By holding a lock that task needs before that save happen, we can delay it until after indexing has completed.
This replaces the previous method of deleting the task, then creating a new task after the indexing was completed.
Requires #1181

Do not schedule a duplicate `save_all_media_for_source` task

---

tubesync/common/errors.py
tubesync/sync/models/media.py
tubesync/sync/models/media__tasks.py
tubesync/sync/tasks.py
tubesync/sync/youtube.py
tubesync/tubesync/settings.py

The `YOUTUBE_DL_SKIP_UNAVAILABLE_FORMAT` setting must be `True` to test/use the new behavior.

Download other formats on failure

---

tubesync/tubesync/settings.py

This avoids a new warning that doesn't apply to our environment anyway.

Set `update_self` to `False` instead of `None`

---

tubesync/sync/choices.py

Changing the example URLs to a more positive message.
The case for showing your support as an obstacle to anti-consumer practices: https://youtu.be/2_Dtmpe9qaQ

Clippy simply wanted to help
